local set = vim.o
set.number = true
set.relativenumber = true
set.tabstop = 4
set.softtabstop = 4
set.expandtab = true
set.shiftwidth = 4
set.autoindent = true
vim.g.splitright = true
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.o.signcolumn = "yes:4"
