local set = vim.o
local setg = vim.g
set.number = true
set.relativenumber = true
set.tabstop = 4
set.softtabstop = 4
set.expandtab = true
set.shiftwidth = 4
set.autoindent = true
set.signcolumn = "yes:4"
set.backup = false
set.cmdheight = 0
set.termguicolors = true
set.swapfile = false
setg.splitright = true
setg.loaded_netrw = 1
setg.loaded_netrwPlugin = 1
